# Generated by Django 5.0.2 on 2024-02-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IngestFromSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=100,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(choices=[("youtube", "Youtube")], max_length=100),
                ),
                ("source_url", models.URLField()),
                ("title", models.CharField(max_length=1024)),
                ("authors", models.CharField(max_length=1024)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
