# Generated by Django 5.0.2 on 2024-02-13 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingest", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingestfromsource",
            name="audio_path",
            field=models.FileField(blank=True, upload_to="ingest/audio/"),
        ),
        migrations.AddField(
            model_name="ingestfromsource",
            name="summary_path",
            field=models.FileField(blank=True, upload_to="ingest/summaries/"),
        ),
        migrations.AddField(
            model_name="ingestfromsource",
            name="transcript_path",
            field=models.FileField(blank=True, upload_to="ingest/transcripts/"),
        ),
    ]
