# Generated by Django 5.0.2 on 2024-02-13 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ingest", "0002_ingestfromsource_audio_path_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingestfromsource",
            name="summary_path",
        ),
    ]
