# Generated by Django 5.0.2 on 2024-05-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingest", "0004_alter_ingestfromsource_authors_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingestfromsource",
            name="source_type",
            field=models.CharField(
                choices=[("youtube", "Youtube"), ("webpage", "Webpage")], max_length=100
            ),
        ),
    ]
