# Generated by Django 5.0.2 on 2024-02-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("summarize", "0003_rename_summary_summarizefromingest_summary_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="summarizefromingest",
            name="summary_path",
            field=models.FileField(blank=True, upload_to="summarize/summaries"),
        ),
    ]
